apiVersion: apps/v1
kind: Deployment
metadata:
  name: walter-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walter-api
  template:
    metadata:
      labels:
        app: walter-api
    spec:
      containers:
        - name: walter-api
          image: us-docker.pkg.dev/scrum-team6/walter-api/api-tests
          ports:
            - containerPort: 3000
          resources: 
            limits:
              cpu: ".5"
              memory: "500mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10
            